### ISSUE TITLE
Optional keep count for drafts

### ISSUE THREAD

**Issue by josiahwitheford** [sgpublic/delete-release-action#3]
Hey there,

Any chance of adding an optional keep count for the drafts? Our workflows result in quite a few draft releases being created, and they don't all get published. It would be awesome to keep a few of the most recent drafts, so we can just have this job run on a schedule to tidy up all the old stuff every week.

Cheers
Joey

**Comment by sgpublic** [comment]
Hello, I have added optional keep count for the drafts support and fixed some bugs. The [v1.1](https://github.com/marketplace/actions/delete-releases?version=v1.1) version has been released. You can close this issue if it validates successfully in your workflows.
