### ISSUE TITLE
Not listing all releases

### ISSUE THREAD

**Issue by sconix** [sgpublic/delete-release-action#6]
Currently this action is not listing all releases, it only lists first page and hence wont delete all releases within a long lived repository with many releases.  Also would be nice to get the node version updated to 20 to get rid of the warning.

I could even do a PR to fix both of these, but is this action still maintained and will get a new release if I make the PR?

**Comment by sgpublic** [comment]
Yes! This repository is still maintained and welcome for PRs. Thank you for your interest to this action. I will handle any PRs quickly and publish a new release after testing.
